# generate tables
cd ..

python3 figures_and_tables/paper_generate_table1_summary_stats.py
python3 figures_and_tables/paper_generate_table2_validation.py
python3 figures_and_tables/paper_generate_table3_and_supp_fig2_repeat_catalogs.py
python3 figures_and_tables/paper_generate_table4_indel_stats.py


